export const SETTING_KEYS = {
  PUBLIC_STRIPE: "stpkys",
  PRIVATE_STRIPE: "jwewjr",
  CAPCHA_GOOGLE: "ECPTCHP",
  OAUTH_GITHUB: "LOGVGTS",
  OAUTH_GOOGLE: "LOGVAGG",
  OAUTH_FACEBOOK: "LOGVAFB",
  SIGN_IN_LIMIT: "LGONLIG",
  MAX_FILE_SIZE_UPLOAD: "MXULDFE",
  UPLOAD_PER_TIME: "MUPEAPD",
  UPLOAD_PER_DAY: "MUPFAPD"
};
